import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header">
          <Link href={"/"}>Home</Link>
          <Link href={"/Cartadelgiorno"}>Carta del giorno</Link>
          <Link href={"/Ruotadellanno"}>Ruota dell'anno</Link>
          <Link href={"/Stesaatre"}>Stesa a tre carte</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
