import type { Metadata } from "next";
import { Geist, Geist_Mono, Arimo, Roboto_Mono, UnifrakturMaguntia, Bodoni_Moda } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bodoni = Bodoni_Moda ({
  variable: "--font-bodoni",
  weight: ["400", "700"],
  subsets: ["latin"]
})

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arimo"
})

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--font-roboto-mono"
})

const unifraktur = UnifrakturMaguntia({
  subsets: ["latin"],
  weight: "400", // questo font ha solo un peso
  variable: "--font-unifraktur"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arimo.variable} ${robotoMono.variable} ${unifraktur.variable} ${bodoni.variable} antialiased`}
      >
        <header>
          <div className="nav">
            <Link href={"/"}>Home</Link>
            <Link href={"/Cartadelgiorno"}>Carta del giorno</Link>
            <Link href={"/Ruotadellanno"}>Ruota dell'anno</Link>
            <Link href={"/Stesaatre"}>Stesa a tre carte</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
